### ISSUE TITLE
napcat startup不能生效

### ISSUE THREAD

**Issue by Chuyu2020** [NapNeko/NapCat-Installer#26]
napcat startup执行后在机器重启后还是不能开机自启动
![80b8225f3ce1a25dee90acc8fe722680](https://github.com/user-attachments/assets/902f2080-7efa-4b19-b444-1ac359ea6134)
![cdef8a616ab476a09967f9f33eaacca0](https://github.com/user-attachments/assets/a787d2e9-a177-4f8f-a753-421ac0b8eaee)

**Comment by Fahaxikiii** [comment]
> napcat startup执行后在机器重启后还是不能开机自启动 ![80b8225f3ce1a25dee90acc8fe722680](https://private-user-images.githubusercontent.com/70002924/381562755-902f2080-7efa-4b19-b444-1ac359ea6134.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTU2NDUsIm5iZiI6MTczMDI5NTM0NSwicGF0aCI6Ii83MDAwMjkyNC8zODE1NjI3NTUtOTAyZjIwODAtN2VmYS00YjE5LWI0NDQtMWFjMzU5ZWE2MTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDEzMzU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMmExMWZlYmJlNDdjY2NlMzNmZjM2NWRhNzdkMDljNmZhODQ5OWEwM2YxZjY4Njc0MGExYjVjYzAyMzRmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8kEOubfNHmBxctqSgi83U0-8cFV_VNGjp2BarHUqjTo) ![cdef8a616ab476a09967f9f33eaacca0](https://private-user-images.githubusercontent.com/70002924/381563892-a787d2e9-a177-4f8f-a753-421ac0b8eaee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTU2NDUsIm5iZiI6MTczMDI5NTM0NSwicGF0aCI6Ii83MDAwMjkyNC8zODE1NjM4OTItYTc4N2QyZTktYTE3Ny00ZjhmLWE3NTMtNDIxYWMwYjhlYWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDEzMzU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMWE1NWJkNmRlNDYxM2QxNGJmNzFjMTIzMTUxZjhhMzU0ZWRiNTYzYmE0OGVhNzU2YWMwMTE2MzRlYzVjOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rJNmOUjmrTJdMeY0o17R103uOaDGI6SO3KuuBIKyQeo)

输入service napcat_QQ号 status查看一下状态

**Comment by Chuyu2020** [comment]
> > napcat startup执行后在机器重启后还是不能开机自启动![80b8225f3ce1a25dee90acc8fe722680](https://private-user-images.githubusercontent.com/70002924/381562755-902f2080-7efa-4b19-b444-1ac359ea6134.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTU2NDUsIm5iZiI6MTczMDI5NTM0NSwicGF0aCI6Ii83MDAwMjkyNC8zODE1NjI3NTUtOTAyZjIwODAtN2VmYS00YjE5LWI0NDQtMWFjMzU5ZWE2MTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDEzMzU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMmExMWZlYmJlNDdjY2NlMzNmZjM2NWRhNzdkMDljNmZhODQ5OWEwM2YxZjY4Njc0MGExYjVjYzAyMzRmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8kEOubfNHmBxctqSgi83U0-8cFV_VNGjp2BarHUqjTo) ![cdef8a616ab476a09967f9f33eaacca0](https://private-user-images.githubusercontent.com/70002924/381563892-a787d2e9-a177-4f8f-a753-421ac0b8eaee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTU2NDUsIm5iZiI6MTczMDI5NTM0NSwicGF0aCI6Ii83MDAwMjkyNC8zODE1NjM4OTItYTc4N2QyZTktYTE3Ny00ZjhmLWE3NTMtNDIxYWMwYjhlYWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDEzMzU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMWE1NWJkNmRlNDYxM2QxNGJmNzFjMTIzMTUxZjhhMzU0ZWRiNTYzYmE0OGVhNzU2YWMwMTE2MzRlYzVjOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rJNmOUjmrTJdMeY0o17R103uOaDGI6SO3KuuBIKyQeo)
> 
> 输入service napcat_QQ号 status查看一下状态

使用sudo systemctl enable 开启napcat_QQ号.service 的服务后，QQ在重启后运行，DLC未能开机自启，请问也需要开启对应的服务吗，具体是什么服务名
![fe1aa4b9ee7a9cd148dfae4f8ada5ad5](https://github.com/user-attachments/assets/60d37989-96cf-4630-9466-7f856436531d)

**Comment by Fahaxikiii** [comment]
> > > napcat startup执行后在机器重启后还是不能开机自启动![80b8225f3ce1a25dee90acc8fe722680](https://private-user-images.githubusercontent.com/70002924/381562755-902f2080-7efa-4b19-b444-1ac359ea6134.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTU2NDUsIm5iZiI6MTczMDI5NTM0NSwicGF0aCI6Ii83MDAwMjkyNC8zODE1NjI3NTUtOTAyZjIwODAtN2VmYS00YjE5LWI0NDQtMWFjMzU5ZWE2MTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDEzMzU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMmExMWZlYmJlNDdjY2NlMzNmZjM2NWRhNzdkMDljNmZhODQ5OWEwM2YxZjY4Njc0MGExYjVjYzAyMzRmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8kEOubfNHmBxctqSgi83U0-8cFV_VNGjp2BarHUqjTo) ![cdef8a616ab476a09967f9f33eaacca0](https://private-user-images.githubusercontent.com/70002924/381563892-a787d2e9-a177-4f8f-a753-421ac0b8eaee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTU2NDUsIm5iZiI6MTczMDI5NTM0NSwicGF0aCI6Ii83MDAwMjkyNC8zODE1NjM4OTItYTc4N2QyZTktYTE3Ny00ZjhmLWE3NTMtNDIxYWMwYjhlYWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDEzMzU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMWE1NWJkNmRlNDYxM2QxNGJmNzFjMTIzMTUxZjhhMzU0ZWRiNTYzYmE0OGVhNzU2YWMwMTE2MzRlYzVjOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rJNmOUjmrTJdMeY0o17R103uOaDGI6SO3KuuBIKyQeo)
> > 
> > 
> > 输入service napcat_QQ号 status查看一下状态
> 
> 使用sudo systemctl enable 开启napcat_QQ号.service 的服务后，QQ在重启后运行，DLC未能开机自启，请问也需要开启对应的服务吗，具体是什么服务名 ![fe1aa4b9ee7a9cd148dfae4f8ada5ad5](https://private-user-images.githubusercontent.com/70002924/381577954-60d37989-96cf-4630-9466-7f856436531d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTczNjIsIm5iZiI6MTczMDI5NzA2MiwicGF0aCI6Ii83MDAwMjkyNC8zODE1Nzc5NTQtNjBkMzc5ODktOTZjZi00NjMwLTk0NjYtN2Y4NTY0MzY1MzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE0MDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ODg5MmY2MTM3ODgyNmQzNjBhMmEwZDMzMTE2ZDMwNTQ3MjkxOTAwZjdlYjA0NGE3NTJhZWJhYjVjOGY0N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.js5GmzR_HLxzBd0PLtVHW6YfY6_BhSoJT0dWgEvfQ94)

已修复，不是systemctl，是SysVinit,创建在/etc/init.d/目录下。然后我说错了，服务名以 nc_QQ号 命名（如：nc_12345）。输入 service nc_QQ号 status 可以查看状态
![image](https://github.com/user-attachments/assets/4b989d31-1baa-4cab-aee3-079d71fbcdde)

**Comment by Chuyu2020** [comment]
解决
