### ISSUE TITLE
linux一键安装失败

### ISSUE THREAD

**Issue by ouostar** [NapNeko/NapCat-Installer#28]
[2024-11-02 10:58:06]: 当前系统架构: amd64
[2024-11-02 10:58:06]: 正在更新依赖...
[2024-11-02 10:58:06]: 安装epel中...                                       Last metadata expiration check: 1:06:28 ago on Sat 02 Nov 2024 09:51:39 AM CST.
No match for argument: epel-release
Error: Unable to find a match: epel-release                                [2024-11-02 10:58:07]: 安装epel (sudo yum install -y epel-release)成功     [2024-11-02 10:58:07]: 安装zip unzip jq curl xorg-x11-server-Xvfb screen procps-ng中...
[Last](url) metadata expiration check: 1:06:28 ago on Sat 02 Nov 2024 09:51:39 AM CST.
Package zip-3.0-30.el9.x86_64 is already installed.                        Package unzip-6.0-53.el9.x86_64 is already installed.
Package curl-7.76.1-31.el9.x86_64 is already installed.                    No match for argument: screen                                              Package procps-ng-3.3.17-4.el9.x86_64 is already installed.
Error: Unable to find a match: screen
[2024-11-02 10:58:07]: 安装zip unzip jq curl xorg-x11-server-Xvfb screen procps-ng (sudo yum install -y zip unzip jq curl xorg-x11-server-Xvfb screen procps-ng)成功                                                             napcat.sh: line 346: jq: command not found
napcat.sh: line 347: jq: command not found                                 [2024-11-02 10:58:08]: 无法获取远程QQ版本, 请检查错误。
系统 CentOS Stream 9 使用shell安装时失败

**Comment by Fahaxikiii** [comment]
> [2024-11-02 10:58:06]: 当前系统架构: amd64 [2024-11-02 10:58:06]: 正在更新依赖... [2024-11-02 10:58:06]: 安装epel中... Last metadata expiration check: 1:06:28 ago on Sat 02 Nov 2024 09:51:39 AM CST. No match for argument: epel-release Error: Unable to find a match: epel-release [2024-11-02 10:58:07]: 安装epel (sudo yum install -y epel-release)成功 [2024-11-02 10:58:07]: 安装zip unzip jq curl xorg-x11-server-Xvfb screen procps-ng中... [Last](url) metadata expiration check: 1:06:28 ago on Sat 02 Nov 2024 09:51:39 AM CST. Package zip-3.0-30.el9.x86_64 is already installed. Package unzip-6.0-53.el9.x86_64 is already installed. Package curl-7.76.1-31.el9.x86_64 is already installed. No match for argument: screen Package procps-ng-3.3.17-4.el9.x86_64 is already installed. Error: Unable to find a match: screen [2024-11-02 10:58:07]: 安装zip unzip jq curl xorg-x11-server-Xvfb screen procps-ng (sudo yum install -y zip unzip jq curl xorg-x11-server-Xvfb screen procps-ng)成功 napcat.sh: line 346: jq: command not found napcat.sh: line 347: jq: command not found [2024-11-02 10:58:08]: 无法获取远程QQ版本, 请检查错误。 系统 CentOS Stream 9 使用shell安装时失败

centos这部分我的服务器没有9系的系统重装，没办法测，而且不是我写的。你可以尝试手动安装jq和xorg-x11-server-Xvfb这两个包，screen是非必须的（用来后台运行的），我晚上用电脑跑虚拟机测一下

**Comment by Fahaxikiii** [comment]
> [2024-11-02 10:58:06]: 当前系统架构: amd64
> [2024-11-02 10:58:06]: 正在更新依赖...
> [2024-11-02 10:58:06]: 安装epel中...                                       Last metadata expiration check: 1:06:28 ago on Sat 02 Nov 2024 09:51:39 AM CST.
> No match for argument: epel-release
> Error: Unable to find a match: epel-release                                [2024-11-02 10:58:07]: 安装epel (sudo yum install -y epel-release)成功     [2024-11-02 10:58:07]: 安装zip unzip jq curl xorg-x11-server-Xvfb screen procps-ng中...
> [Last](url) metadata expiration check: 1:06:28 ago on Sat 02 Nov 2024 09:51:39 AM CST.
> Package zip-3.0-30.el9.x86_64 is already installed.                        Package unzip-6.0-53.el9.x86_64 is already installed.
> Package curl-7.76.1-31.el9.x86_64 is already installed.                    No match for argument: screen                                              Package procps-ng-3.3.17-4.el9.x86_64 is already installed.
> Error: Unable to find a match: screen
> [2024-11-02 10:58:07]: 安装zip unzip jq curl xorg-x11-server-Xvfb screen procps-ng (sudo yum install -y zip unzip jq curl xorg-x11-server-Xvfb screen procps-ng)成功                                                             napcat.sh: line 346: jq: command not found
> napcat.sh: line 347: jq: command not found                                 [2024-11-02 10:58:08]: 无法获取远程QQ版本, 请检查错误。
> 系统 CentOS Stream 9 使用shell安装时失败
使用dnf这个包管理器试试？要开启epel这个源才能安装这两个包sudo dnf install epel-release
sudo dnf update
sudo dnf install -y jq xorg-x11-server-Xvfb

**Comment by Fahaxikiii** [comment]
> [2024-11-02 10:58:06]: 当前系统架构: amd64
> [2024-11-02 10:58:06]: 正在更新依赖...
> [2024-11-02 10:58:06]: 安装epel中...                                       Last metadata expiration check: 1:06:28 ago on Sat 02 Nov 2024 09:51:39 AM CST.
> No match for argument: epel-release
> Error: Unable to find a match: epel-release                                [2024-11-02 10:58:07]: 安装epel (sudo yum install -y epel-release)成功     [2024-11-02 10:58:07]: 安装zip unzip jq curl xorg-x11-server-Xvfb screen procps-ng中...
> [Last](url) metadata expiration check: 1:06:28 ago on Sat 02 Nov 2024 09:51:39 AM CST.
> Package zip-3.0-30.el9.x86_64 is already installed.                        Package unzip-6.0-53.el9.x86_64 is already installed.
> Package curl-7.76.1-31.el9.x86_64 is already installed.                    No match for argument: screen                                              Package procps-ng-3.3.17-4.el9.x86_64 is already installed.
> Error: Unable to find a match: screen
> [2024-11-02 10:58:07]: 安装zip unzip jq curl xorg-x11-server-Xvfb screen procps-ng (sudo yum install -y zip unzip jq curl xorg-x11-server-Xvfb screen procps-ng)成功                                                             napcat.sh: line 346: jq: command not found
> napcat.sh: line 347: jq: command not found                                 [2024-11-02 10:58:08]: 无法获取远程QQ版本, 请检查错误。
> 系统 CentOS Stream 9 使用shell安装时失败

使用以下命令强制安装sudo dnf --allowerasing install -y zip unzip jq curl xorg-x11-server-Xvfb screen procps-ng

**Comment by Fahaxikiii** [comment]
已修改

**Comment by ouostar** [comment]
已解决
