### ISSUE TITLE
linux一键安装没有检测是否已经安装完成linuxQQ，导致如果重复运行会重复安装

### ISSUE THREAD

**Issue by Mitpoppy** [NapNeko/NapCat-Installer#3]

**Comment by flyqie** [comment]
已通过[42d1ce2](https://github.com/NapNeko/NapCat-Installer/commit/42d1ce2429784fb514838a4c7d80c3a3a784e4f9)解决

**Comment by Mitpoppy** [comment]
> 已通过[42d1ce2](https://github.com/NapNeko/NapCat-Installer/commit/42d1ce2429784fb514838a4c7d80c3a3a784e4f9)解决

好评！
